name: fitsize
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.0-26.0.dev <4.0.0'

dependencies:
  flutter_switch: ^0.3.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  beamer: ^1.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Bold.ttf
    - family: Fors
      fonts:
        - asset: assets/fonts/TT-Fors-Trial-Bold.ttf
    - family: ForsThin
      fonts:
        - asset: assets/fonts/TT Fors Trial Light.ttf
    - family: ForsLight
      fonts:
        - asset: assets/fonts/TT Fors Trial Regular.ttf    