name: fitsize
description: Fitsize.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  beamer: ^1.5.2
  camera: ^0.10.5+5
  video_player: ^2.2.14
  path_provider: ^2.0.5
  image_picker: ^1.0.4
  getwidget: ^4.0.0
  video_viewer: ^1.2.7
  html: ^0.15.0
  vertical_weight_slider: ^2.5.1
  rulers: ^1.0.7
  flutter_ruler_picker: ^1.0.6
  app_settings: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/tuto.mp4
    - assets/videos/tuto2.mp4
    - assets/iconSVG/icon_man.svg
    - assets/iconSVG/icon_manDark.svg
    - assets/iconSVG/icon_woman.svg
    - assets/iconSVG/icon_womanDark.svg
    - assets/iconSVG/basil_other-1-outline.svg
    - assets/iconSVG/basil_other-1-outlineDark.svg
    - assets/iconSVG/selfie.svg
    - assets/iconSVG/selfieDark.svg
    - assets/iconSVG/parAmi.svg
    - assets/iconSVG/parAmiDark.svg

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Bold.ttf
    - family: Fors
      fonts:
        - asset: assets/fonts/TT-Fors-Trial-Bold.ttf
    - family: ForsThin
      fonts:
        - asset: assets/fonts/TT Fors Trial Light.ttf
    - family: ForsLight
      fonts:
        - asset: assets/fonts/TT Fors Trial Regular.ttf
